USE mydb;
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('et,','elit erat vitae risus. Duis a mi fringilla','438','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('luctus','Etiam gravida molestie arcu. Sed eu','100','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('quis,','feugiat. Sed nec metus facilisis lorem','379','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ligula','posuere vulputate, lacus. Cras interdum. Nunc','394','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Nam','Nullam velit dui, semper et,','431','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('bibendum','ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis','500','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ipsum.','Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla','496','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('consectetuer','cubilia Curae; Donec tincidunt. Donec vitae erat','271','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('fringilla','tortor at risus. Nunc ac sem','87','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('blandit','adipiscing lobortis risus. In mi pede, nonummy ut, molestie','342','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Maecenas','tellus faucibus leo, in lobortis tellus justo','369','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('nec','lacus. Mauris non dui nec urna suscipit','152','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('turpis.','Proin mi. Aliquam gravida mauris ut mi.','85','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('vestibulum,','ipsum nunc id enim. Curabitur','90','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('arcu.','fringilla cursus purus. Nullam scelerisque neque sed sem','229','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ipsum','non, luctus sit amet, faucibus ut,','493','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Sed','Sed id risus quis diam luctus lobortis.','289','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('risus.','semper, dui lectus rutrum urna, nec','366','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('risus','ullamcorper. Duis at lacus. Quisque','427','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('egestas','quis massa. Mauris vestibulum, neque sed','203','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ullamcorper','velit eget laoreet posuere, enim nisl elementum purus, accumsan interdum','487','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Morbi','mattis. Cras eget nisi dictum augue malesuada malesuada. Integer','87','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Phasellus','odio. Aliquam vulputate ullamcorper magna.','341','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('urna','velit justo nec ante. Maecenas mi','360','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('convallis','dolor. Quisque tincidunt pede ac urna. Ut tincidunt','243','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Morbi','turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis','367','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('purus.','risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non','91','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('mus.','eros non enim commodo hendrerit. Donec porttitor tellus non magna.','111','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('diam.','turpis vitae purus gravida sagittis. Duis gravida. Praesent','218','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('et','sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean','393','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('nisl.','Suspendisse dui. Fusce diam nunc, ullamcorper','214','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ut','Cum sociis natoque penatibus et magnis dis parturient montes,','71','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('eget','molestie pharetra nibh. Aliquam ornare, libero','163','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('est,','Proin vel arcu eu odio tristique pharetra. Quisque ac libero','342','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('eleifend','pellentesque, tellus sem mollis dui, in sodales elit erat vitae','267','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ipsum','quam quis diam. Pellentesque habitant morbi tristique','292','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('dolor','turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus.','193','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('vulputate','sit amet risus. Donec egestas. Aliquam nec enim. Nunc','400','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('nec,','dictum. Phasellus in felis. Nulla tempor augue ac ipsum.','417','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('dis','ut erat. Sed nunc est, mollis non, cursus non, egestas','491','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ornare.','est ac facilisis facilisis, magna tellus faucibus','42','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('lacus.','at, velit. Cras lorem lorem,','46','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('lacus.','est. Nunc ullamcorper, velit in aliquet lobortis,','400','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('aliquam','dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu','97','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('dictum','eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies','365','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('vel','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean','391','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ipsum','in aliquet lobortis, nisi nibh','350','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Nam','faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas.','413','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Ut','risus. Donec egestas. Duis ac arcu.','357','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('enim.','ac mattis ornare, lectus ante dictum mi, ac mattis','394','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('sapien.','mus. Donec dignissim magna a tortor.','92','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Phasellus','sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus','361','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('lorem','tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem,','240','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Lorem','Nulla facilisi. Sed neque. Sed','37','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('accumsan','nisi. Aenean eget metus. In','144','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('nunc','Integer id magna et ipsum cursus vestibulum.','25','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('enim.','et magnis dis parturient montes, nascetur ridiculus mus.','114','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Duis','quam. Curabitur vel lectus. Cum sociis natoque','491','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('iaculis','libero. Proin mi. Aliquam gravida mauris ut mi. Duis','481','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('molestie','taciti sociosqu ad litora torquent per conubia nostra, per','348','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('lorem','neque sed sem egestas blandit. Nam nulla magna, malesuada','115','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('sapien.','erat volutpat. Nulla dignissim. Maecenas ornare','105','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('id,','sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum','59','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('egestas.','dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat','269','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('non,','est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed','262','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('massa','Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie','438','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('pede.','aliquet diam. Sed diam lorem,','101','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('sed','placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla','354','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('risus.','vitae erat vel pede blandit congue.','455','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('nec','orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam','36','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Vivamus','dictum. Proin eget odio. Aliquam vulputate ullamcorper magna.','53','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('accumsan','Donec egestas. Aliquam nec enim. Nunc ut erat. Sed','217','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('dictum','porttitor tellus non magna. Nam ligula elit, pretium et,','78','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('in','auctor, nunc nulla vulputate dui, nec tempus','171','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('metus','adipiscing non, luctus sit amet, faucibus','257','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('a','tempor lorem, eget mollis lectus pede','441','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('augue','egestas. Sed pharetra, felis eget varius ultrices, mauris','151','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('posuere','Maecenas iaculis aliquet diam. Sed diam','27','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('vulputate,','metus. Vivamus euismod urna. Nullam lobortis quam a felis','261','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('nibh.','sed leo. Cras vehicula aliquet libero.','29','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('non,','et netus et malesuada fames ac turpis egestas. Aliquam','22','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('tellus,','tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec','435','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Nam','pede, ultrices a, auctor non,','276','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ut','nisi. Cum sociis natoque penatibus et magnis','173','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('amet','natoque penatibus et magnis dis parturient','246','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('egestas.','iaculis odio. Nam interdum enim non nisi. Aenean eget','349','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ac','ullamcorper. Duis cursus, diam at pretium','289','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('ante','sem, vitae aliquam eros turpis non enim. Mauris','212','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('eget','a purus. Duis elementum, dui','104','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('pellentesque,','aliquam eros turpis non enim.','160','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('orci','dolor. Nulla semper tellus id nunc interdum','497','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('eleifend','nascetur ridiculus mus. Donec dignissim magna','317','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('semper,','ornare. Fusce mollis. Duis sit amet diam','63','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Sed','accumsan convallis, ante lectus convallis','344','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('tincidunt','non magna. Nam ligula elit, pretium et, rutrum','174','4');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('luctus','gravida. Aliquam tincidunt, nunc ac','206','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('Phasellus','Nam nulla magna, malesuada vel,','98','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('dictum','nascetur ridiculus mus. Proin vel arcu eu odio tristique','235','3');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('sit','commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa','270','2');
INSERT INTO `produits` (`libelle`,`description`,`prix`,`categories_id`) VALUES ('lobortis','Vivamus sit amet risus. Donec','42','4');