USE mydb;
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('56','6509 Ligula. Road','M6D 3B3','Frederiksted','1','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('94','8816 Etiam Road','W5G 3F1','Ephraim','2','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('50','P.O. Box 204, 3264 Non, Avenue','T3J 4J7','Honolulu','3','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('3','Ap #553-4829 Netus Rd.','J4Z 6Q1','Rancho Santa Margarita','4','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('39','351-6019 Phasellus Rd.','E4V 6S1','Eugene','5','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('90','Ap #930-6651 Nec St.','K1J 4Q9','Muncie','6','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('89','344-8942 Vestibulum Rd.','W1I 7Q0','Truth or Consequences','7','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('13','409-1521 Mattis. St.','J6Z 7Z6','Plainfield','8','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('100','Ap #966-8165 Magna. Rd.','Y7O 3K2','Fallon','9','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('14','718-4669 Orci St.','Q8B 6O0','Dalton','10','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('60','P.O. Box 835, 8107 Ligula. Av.','I7Q 9Z0','Brigham City','11','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('38','631-3866 Rhoncus. Ave','C1U 2P3','Claremore','12','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('59','907-8503 Feugiat. St.','V2Z 5B9','Mentor','13','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('27','4261 Dictum Road','I4C 4E2','West Hartford','14','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('41','P.O. Box 827, 5088 Tortor, St.','R7X 8S4','Temple City','15','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('96','4708 Accumsan Avenue','H5G 7O5','Sierra Vista','16','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('55','458-3677 Cum St.','X4U 6I6','Hampton','17','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('50','Ap #122-5852 Et Ave','Y8M 2O0','San Bernardino','18','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('83','P.O. Box 692, 1245 Arcu Ave','U1U 6R1','Compton','19','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('90','Ap #317-1268 Aliquam St.','G1B 7G6','Salt Lake City','20','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('1','Ap #654-348 Lobortis Road','Z8W 8K5','Warren','21','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('56','Ap #484-5218 Metus. Street','P7V 6N0','Escondido','22','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('11','109-5299 Molestie Avenue','W5I 7H7','Dixon','23','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('29','Ap #486-5112 Adipiscing St.','E1W 1T3','Berkeley','24','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('69','Ap #685-3438 Dictum Street','D2Q 5X9','Chelsea','25','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('19','108-3572 Non, Avenue','C5W 9O6','Geneva','26','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('70','P.O. Box 650, 4703 Sapien, Av.','T6O 4B4','Franklin','27','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('59','Ap #790-6774 Tellus. Rd.','O7K 4S9','Bend','28','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('59','814-6768 Donec St.','D4M 7U5','Charlotte','29','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('76','323-3559 Scelerisque Rd.','C9W 5I5','La Palma','30','2');