-- INSERT adresses
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('56','6509 Ligula. Road','M6D 3B3','Frederiksted','1','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('94','8816 Etiam Road','W5G 3F1','Ephraim','31','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('50','P.O. Box 204, 3264 Non, Avenue','T3J 4J7','Honolulu','61','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('3','Ap #553-4829 Netus Rd.','J4Z 6Q1','Rancho Santa Margarita','91','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('39','351-6019 Phasellus Rd.','E4V 6S1','Eugene','121','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('90','Ap #930-6651 Nec St.','K1J 4Q9','Muncie','151','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('89','344-8942 Vestibulum Rd.','W1I 7Q0','Truth or Consequences','181','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('13','409-1521 Mattis. St.','J6Z 7Z6','Plainfield','211','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('100','Ap #966-8165 Magna. Rd.','Y7O 3K2','Fallon','241','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('14','718-4669 Orci St.','Q8B 6O0','Dalton','271','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('60','P.O. Box 835, 8107 Ligula. Av.','I7Q 9Z0','Brigham City','301','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('38','631-3866 Rhoncus. Ave','C1U 2P3','Claremore','331','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('59','907-8503 Feugiat. St.','V2Z 5B9','Mentor','361','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('27','4261 Dictum Road','I4C 4E2','West Hartford','391','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('41','P.O. Box 827, 5088 Tortor, St.','R7X 8S4','Temple City','421','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('96','4708 Accumsan Avenue','H5G 7O5','Sierra Vista','451','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('55','458-3677 Cum St.','X4U 6I6','Hampton','481','3');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('50','Ap #122-5852 Et Ave','Y8M 2O0','San Bernardino','511','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('83','P.O. Box 692, 1245 Arcu Ave','U1U 6R1','Compton','541','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('90','Ap #317-1268 Aliquam St.','G1B 7G6','Salt Lake City','571','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('1','Ap #654-348 Lobortis Road','Z8W 8K5','Warren','601','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('56','Ap #484-5218 Metus. Street','P7V 6N0','Escondido','631','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('11','109-5299 Molestie Avenue','W5I 7H7','Dixon','661','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('29','Ap #486-5112 Adipiscing St.','E1W 1T3','Berkeley','691','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('69','Ap #685-3438 Dictum Street','D2Q 5X9','Chelsea','721','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('19','108-3572 Non, Avenue','C5W 9O6','Geneva','751','2');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('70','P.O. Box 650, 4703 Sapien, Av.','T6O 4B4','Franklin','781','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('59','Ap #790-6774 Tellus. Rd.','O7K 4S9','Bend','811','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('59','814-6768 Donec St.','D4M 7U5','Charlotte','841','1');
INSERT INTO `adresses` (`numero`,`voie`,`cp`,`ville`,`utilisateurs_id`,`pays_id`) VALUES ('76','323-3559 Scelerisque Rd.','C9W 5I5','La Palma','871','2');