#!/bin/bash

rm logs/mysql.out && echo "logs effacés"

if [ -d ddl ] ; then
	echo "ddl found"
	if [ -f ddl/create_tables.sql ] ; then
		echo "create_tables.sql found"
		if mysql -h localhost --user=root --password=root < ddl/create_tables.sql >> logs/mysql.out ; then
			echo "schéma créé"
		else
			echo "schéma non créé"
			exit 1
		fi
	else
		echo "create_tables.sql not found"
		exit 1
	fi
else
	echo "ddl not found"
	exit 1
fi

if [ -d dml/insert ] ; then
	echo "dml/insert found"
	for file in dml/insert/insert_*.sql ; do
		echo "$file"
		mysql -h localhost --user=root --password=root < $file >> logs/mysql.out
	done
else
	exit 1
fi

echo "Tout est OK"

echo "Les logs sont dans mysql.out"
