#!/bin/bash

echo "effacer les logs"
rm mysql.out

echo "creation du schema"
mysql -h localhost --user=root --password=root < create_tables.sql >> mysql.out

echo "insert roles"
mysql -h localhost --user=root --password=root < insert_roles.sql >> mysql.out

echo "insert utilisateurs"
mysql -h localhost --user=root --password=root < insert_utilisateurs.sql >> mysql.out

echo "insert pays"
mysql -h localhost --user=root --password=root < insert_pays.sql >> mysql.out

echo "insert adresses"
mysql -h localhost --user=root --password=root < insert_adresses.sql >> mysql.out

echo "insert cartes_credit"
mysql -h localhost --user=root --password=root < insert_cartes_credit.sql >> mysql.out

echo "insert categories"
mysql -h localhost --user=root --password=root < insert_categories.sql >> mysql.out

echo "insert etapes"
mysql -h localhost --user=root --password=root < insert_etapes.sql >> mysql.out

echo "insert methodes_livraison"
mysql -h localhost --user=root --password=root < insert_methodes_livraison.sql >> mysql.out



echo "Tout est OK"
echo "Les logs sont dans mysql.out"
